### ISSUE TITLE
Self-Test Snapshot can cause window to become too large vertically and window won't re-size or scroll

### ISSUE THREAD

**Issue by vatbrain** [TytanRock/PenguinTuner#15]
When using the Self-Test Snapshot feature on a TalonSRX with a connected Mag Encoder, the Penguin Tuner window is automatically re-sized to a size that is too large vertically for a 1080p monitor, and it cannot be re-sized or scrolled to see the information at the bottom of the Self-Test Snapshot tab, or to access the Self-Test Snapshot button at the bottom of the tab to perform additional Self-Test Snapshots.

**Comment by TytanRock** [comment]
Check out the branch https://github.com/TytanRock/PenguinTuner/tree/snapshot-scroll and let me know how it is.
It wraps the self-test snapshot text box in a scrollbar window with both horizontal and vertical scroll, from my testing it doesn't automatically resize the window so it should be what you want.

Keep in mind if you're compiling for pi, keep using the shared object I provided in the other issue. I'm close to getting pi support but not there quite yet.

**Comment by vatbrain** [comment]
I tried it out and it worked well once. However, when I attempted to perform a second Self-Test Snapshot by using the button at the bottom of the window, it crashed the application.  In order to get it working a second time, I had to completely power down the motor controller, and re-boot the pi. It took me several re-boots to be able to repeat the experiment.
It seems to me like the whole Phoenix diagnostic server system is fundamentally non-robust on the pi,  as I have similar problems when running Phoenix Tuner on Windows and connecting to the pi via a network.
In my opinion, it would be better to have an app that runs native on a linux host system that just deals directly with the devices attached via socketCAN. Having to run this extra diagnostic server seems to be a source of a lot of problems, and the benefit is not yet clear to me.

**Comment by TytanRock** [comment]
That may be the case, I haven't been able to set up my test bench with the raspberry pi yet, so most of my testing has been excluding the diagnostic server.

When you say performing a second Self-Test Snapshot crashes the application, do you mean the Penguin Tuner application crashes, or the robot application that contains the diagnostic server? In either case, I'll get my test bench set up to reproduce this and figure out what's going on.

Regarding the purpose of diagnostic server being external to Penguin Tuner, I've responded [here](https://github.com/TytanRock/PenguinTuner/issues/11#issuecomment-711420332), let me know if you have other questions regarding it in the other issue.

**Comment by vatbrain** [comment]
Penguin Tuner application crashes. Window disappears.

**Comment by vatbrain** [comment]
This morning I discovered that performing a second Self-Test Snapshot did not crash Penguin Tuner when two motor controllers were attached to the CAN network, but when I disconnected one motor controller from the CAN network and performed two Self-Test Snapshots in a row, Penguin Tuner crashed.
However, after re-starting Penguin Tuner with only one motor controller attached and performing two Self-Test Snapshots in a row, Penguin Tuner did NOT crash again. So the behavior is not completely consistent.

**Comment by vatbrain** [comment]
I am running with the following code, derived from the CTR Electronics SocketCAN example, to create my diagnostic server:
```
////////////////////////////////////////
//
// Minimal app to cause a Phoenix diagnostic server to be run.
//
////////////////////////////////////////

#define Phoenix_No_WPI // remove WPI dependencies
#include "ctre/phoenix/platform/Platform.h"
#include "ctre/phoenix/cci/Unmanaged_CCI.h"
#include <string>
#include <chrono>
#include <thread>
#include <unistd.h>

using namespace ctre::phoenix;
using namespace ctre::phoenix::platform;

/** simple wrapper for code cleanup */
void sleepApp(int ms)
{
        std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

int main() {
        std::string interface;
        interface = "can0";
        ctre::phoenix::platform::can::SetCANInterface(interface.c_str());

        c_SetPhoenixDiagnosticsStartTime(0); // we will use the diag server this application installs

        while (true) {
                sleepApp(20);
        }
        return 0;
}

**Comment by TytanRock** [comment]
I was able to reproduce and found the issue. Good catch! It was indicative of a much larger issue I had with how I handled the backend updating the frontend. It should be fixed in the latest commit of snapshot-scroll, and I verified with my own pi self-testing a Victor SPX. Before I was able to reproduce on the second or third self-test, and so far I've done 10 in 10 tests without a failure.
